site_name: KubeEdge Docs
docs_dir: docs/
pages:
    - Home: index.md
    - Guides:
        - 'Unit Test Guide': guides/unit_test_guide.md
        - 'MQTT Message Topics': guides/message_topics.md
    - Concepts:
        - 'What is KubeEdge': kubeedge.md
        - 'Beehive': modules/beehive.md
        - 'EventBus': modules/eventbus.md
        - 'MetaManager': modules/metamanager.md
        - 'EdgeHub': modules/edgehub.md
        - 'Device Twin': modules/devicetwin.md

    
